[package]
name = "rustypub"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.37"

[dev-dependencies]
anyhow = "1.0.66"
pretty_assertions = "1.3.0"
