[package]
name = "rustypub"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
anyhow = "1.0.66"
pretty_assertions = "1.3.0"
